FROM public.ecr.aws/lambda/python:3.11

# Copiar requirements
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# Instalar dependencias de Python
# Se usa --no-cache-dir para mantener el tamaño de la imagen lo más pequeño posible
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código fuente de la aplicación (solo la carpeta app)
COPY app/ ${LAMBDA_TASK_ROOT}/app/

# Opcional: copiar scripts si necesitas correr seeders en Lambda
# COPY scripts/ ${LAMBDA_TASK_ROOT}/scripts/

# El CMD establece el punto de entrada (handler) de Lambda apuntando a Mangum
CMD ["app.main.handler"]
